version: "3.8"
services:
  backend:
    image: backend-t4go
    volumes:
      - ".:/code"
    ports:
      - 5000:5000
    depends_on:
      - mysqlDatabase

  mysqlDatabase:
    image: my-sqlprueba
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - "3306:3306"

  frontEnd:
    image: frontend-t4go
    volumes:
      - ".:/code"
    ports:
      - 3000:3000
    depends_on:
      - backend
